In [1]:
from utils import *
import numpy as np

In [2]:
X = np.random.randint(10, size=(20, 5))
X

array([[4, 7, 0, 1, 1],
       [3, 7, 7, 5, 3],
       [2, 8, 0, 0, 0],
       [7, 7, 4, 4, 7],
       [1, 9, 4, 6, 7],
       [4, 0, 8, 0, 8],
       [7, 8, 6, 2, 7],
       [6, 7, 3, 2, 7],
       [2, 8, 9, 3, 0],
       [6, 0, 6, 8, 6],
       [1, 8, 1, 0, 5],
       [2, 1, 3, 4, 0],
       [7, 0, 4, 2, 2],
       [3, 1, 3, 8, 2],
       [8, 3, 5, 2, 4],
       [5, 9, 6, 5, 1],
       [3, 2, 9, 7, 2],
       [2, 3, 1, 2, 9],
       [4, 3, 3, 7, 4],
       [9, 5, 0, 0, 8]])

In [3]:
mcar_mask = MCAR_mask(X, 0.3)
mcar_mask

array([[False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False, False, False,  True, False],
       [False, False,  True, False, False],
       [False,  True,  True,  True, False],
       [False, False,  True,  True, False],
       [ True, False, False,  True, False],
       [ True,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False, False,  True,  True, False],
       [False, False,  True,  True, False],
       [False, False,  True, False,  True],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False,  True,  True],
       [ True,  True, False, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [4]:
mar_mask = MAR_mask(X, 0.3, 0.2)
mar_mask

array([[False,  True,  True, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False],
       [False,  True, False,  True, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False,  True,  True, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False,  True,  True,  True, False],
       [False,  True, False,  True, False],
       [ True, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [5]:
mnar_mask = MNAR_mask_logistic(X, 0.3)
mnar_mask

array([[ True,  True, False,  True,  True],
       [ True,  True,  True, False, False],
       [ True,  True, False,  True,  True],
       [False, False,  True, False,  True],
       [False, False,  True, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False,  True, False, False]])